export const GET_USER = 'GET_USER';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const ALL_PROJECTS = 'ALL_PROJECTS';
export const FAVOURITES = 'FAVOURITES';
export const PARTNERSHIP = 'PARTNERSHIP';
export const REMOVE_PARTNERSHIP = 'REMOVE_PARTNERSHIP';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
